### PR TITLE
Add  Ansible-lint suggested fixes

### PR DESCRIPTION
**Pull request by stefanos1316**
I thought of adding a pro-hook commit to perform Ansible-lint.
However, it requires the Ansible version of 2.9 at least.
This version cannot be installed with apt but with pip.
Therefore, if we want to install it with pip, we need to install
python-pip too.

### CODE REVIEW

**Comment by dspinellis** [comment]
Well done!  Regarding the installation of Ansible, can't it be specified as a Python module dependency together with the others we already have?

**Comment by stefanos1316** [comment]
Do you mean that we should install the Ansible for the `venv`too?
In that case, one needs to commit while having the  `venv`  activated in order to use the pre-commit hook
of Ansible-lint which feels a bit weird, no?
Note that we install the Python modules using the Ansible.

**Comment by dspinellis** [comment]
I was thinking to install a more recent version of ansible and ansible lint in venv (as a development dependency) in order to run ansible lint.

**Comment by stefanos1316** [comment]
I think now I get what do you mean.
You are saying that we should make the pre-commit hook to use the Ansible-lint that is installed
in the venv, right?

**Comment by dspinellis** [comment]
Exactly!

23 Dec 2020 01:01:37 Stefanos Georgiou <notifications@github.com>:

**Pull request merged**
