### PR TITLE
Disable WiFi on reboot

### PR DESCRIPTION
**Pull request by stefanos1316**
Issue [#56](https://github.com/eellak/epidose/issues/56)

### CODE REVIEW

**Comment by dspinellis** [comment]
Not sure this is the best way.  Can't you specify a default network configuration where the WiFi is off until brought up?

**Comment by stefanos1316** [comment]
I have searched on the Web but mostly I find how to disable it through the /boot/config.txt
or similarly, the way I did it.
Any idea of how I should search for it?

**Comment by stefanos1316** [comment]
@dspinellis  adding this `@reboot sudo ifdown wlan0`in the crontab can do the job too.

**Comment by dspinellis** [comment]
I was hoping to disable the automatic bringing up of the interface, but I see no obvious method.

**Comment by dspinellis** [comment]
rc.local seems OK.  Please verify that it actually works, because it needs to be executed after the interface is brought up, right?  Then submit the PR (I cannot reopen this one).

**Comment by stefanos1316** [comment]
If we add the `ip link set wlan0 down` in the `rc.local`, it starts the device where the wlan0 has no IP address
and when executing the `ip link set wlan0 up` it allows wlan0 to get an IP address.
This is what you mean by verifying it?

**Comment by dspinellis** [comment]
Yes, OK.

**Pull request closed without merging**
